kubeconfig = "~/Documents/medium/add-user-k8s/config-admin"
#kubeconfig = "~/.kube/config"
kubecontext    = "kubernetes-admin@kubernetes"
username       = "lancelot"
usergroup      = "knight"
admin          = "dragon"
k8s-certs-path = "/etc/kubernetes/pki"